name: dexscreener_flutter
description: "Decentralized Exchange Tokens | Analysis | Predictions | Trends."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.0
  logger: ^1.0.0
  socket_io_client: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.17.0
  purchases_flutter: ^5.0.0
  flutter_animate: ^4.5.0
  magic_sdk: ^6.0.1
  webview_flutter_web: ^0.2.3+2
  # web3auth_flutter: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env
